set linespace=15

set guifont=Fira\ Mono\ Medium\ for\ Powerline:h15
set guioptions-=T " Removes top toolbar
set guioptions-=r " Removes right hand scroll bar
set go-=L " Removes left hand scroll bar
set linespace=15
